HERE WILL BE THE PASSWORD CHANGE / RESET
<br /><br />
// INPUT YOUR EMAIL ADRESS
<br /><br />
WILL RECEIVE AN EMAIL WITH A LINK
<br /><br />
ACCESS THAT ONE-TIME LINK AND CHANGE YOUR PASSWORD.
<br /><br />
YOU MUST ANSWER A SECRET QUESTION / ENTER SOMETHING like birthdate and a CAPTCHA TOO to reset the password.
<br /><br />

<?php
?>